<a href="https://colab.research.google.com/github/fjadidi2001/Artificial_Intelligence_Learning/blob/master/_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

# Step 1: Load the dataset from a text file
def load_dataset(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()
    dataset = [list(map(int, line.split())) for line in lines]
    '''
    This line of code creates a dataset by iterating through each line in the variable `lines`,
    splitting each line into a list of strings,
    converting each string to an integer using the `map` function,
    and then converting the resulting map object into a list.
    The final dataset is a list of lists, with each inner list containing integers parsed from the original lines.
    '''
    return np.array(dataset)
# Provide the correct path to your text file
file_path = '/content/fars.txt'
original_dataset = load_dataset(file_path)

# Step 2: Convert dataset to bipolar encoding based on the specified condition
def convert_to_bipolar_with_condition(dataset):
    return np.where(dataset > 128, -1, 1)

bipolar_dataset = convert_to_bipolar_with_condition(original_dataset)

# Print original and bipolar datasets for verification
print("Original Dataset:")
print(original_dataset)

print("\nBipolar Encoded Dataset:")
print(bipolar_dataset)
# bipolar_dataset.shape


Original Dataset:
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]

Bipolar Encoded Dataset:
[[-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 ...
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]]


In [5]:
# Step 2: Reshape each sequence into a matrix
num_fonts = 7
sequence_length = 17

# Reshape each sequence into a 2D matrix

'''
This line of code reshapes the original dataset into a new matrix dataset.
The "-1" indicates that the first dimension of the new dataset will be inferred based on the total size of the original dataset
and the specified number of fonts and sequence length. This reshaping is useful for preparing the data for input into a neural network,
where the input shape may need to be specified in a certain way.
'''
matrix_dataset = original_dataset.reshape(-1, num_fonts, sequence_length)


# Print the original and matrix datasets for verification
print("Original Dataset:")
print(original_dataset)

print("\nMatrix Dataset:")
print(matrix_dataset)

Original Dataset:
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]

Matrix Dataset:
[[[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]]

 [[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]]

 [[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]]

 ...

 [[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
 

In [6]:
# Step 2: Convert dataset to bipolar encoding based on the specified condition
def convert_to_bipolar_with_condition(dataset):
    return np.where(dataset > 128, -1, 1)

bipolar_dataset = convert_to_bipolar_with_condition(original_dataset)

# Step 3: Reshape each sequence into a matrix
num_fonts = 7
sequence_length = 17

# Reshape each sequence into a 2D matrix
matrix_dataset = bipolar_dataset.reshape(-1, num_fonts, sequence_length)

# Print the original, bipolar, and matrix datasets for verification
print("Original Dataset:")
print(original_dataset)

print("\nBipolar Encoded Dataset:")
print(bipolar_dataset)

print("\nMatrix Dataset:")
print(matrix_dataset)


Original Dataset:
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]

Bipolar Encoded Dataset:
[[-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 ...
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]]

Matrix Dataset:
[[[-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  ...
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]]

 [[-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  ...
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]]

 [[-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  ...
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]]

 ...

 [[-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  ...
  [-1 -1 