<a href="https://colab.research.google.com/github/fjadidi2001/Artificial_Intelligence_Learning/blob/master/final_edit_alphabetProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Step 1: Load the dataset from a text file
def load_dataset(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()
    dataset = [list(map(int, line.split())) for line in lines]
    return np.array(dataset)

file_path = '/content/fars.txt'  # Provide the correct path to your text file
original_dataset = load_dataset(file_path)

# Step 2: Convert dataset to bipolar encoding based on the specified condition
def convert_to_bipolar_with_condition(dataset):
    return np.where(dataset > 128, -1, 1)

bipolar_dataset = convert_to_bipolar_with_condition(original_dataset)

# Print original and bipolar datasets for verification
print("Original Dataset:")
print(original_dataset)

print("\nBipolar Encoded Dataset:")
print(bipolar_dataset)


Original Dataset:
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]

Bipolar Encoded Dataset:
[[-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 ...
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]]


In [2]:
import numpy as np

# Step 1: Load the dataset from a text file
def load_dataset(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()
    dataset = [list(map(int, line.split())) for line in lines]
    return np.array(dataset)

file_path = '/content/fars.txt'  # Replace with the correct path to your text file
original_dataset = load_dataset(file_path)

# Step 2: Reshape each sequence into a matrix
num_fonts = 7
sequence_length = 17

# Reshape each sequence into a 2D matrix

'''
This line of code reshapes the original dataset into a new matrix dataset.
The "-1" indicates that the first dimension of the new dataset will be inferred based on the total size of the original dataset
and the specified number of fonts and sequence length. This reshaping is useful for preparing the data for input into a neural network,
where the input shape may need to be specified in a certain way.
'''
matrix_dataset = original_dataset.reshape(-1, num_fonts, sequence_length)


# Print the original and matrix datasets for verification
print("Original Dataset:")
print(original_dataset)

print("\nMatrix Dataset:")
print(matrix_dataset)


Original Dataset:
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]

Matrix Dataset:
[[[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]]

 [[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]]

 [[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]]

 ...

 [[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
 

In [3]:
import numpy as np

# Step 1: Load the dataset from a text file
def load_dataset(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()
    dataset = [list(map(int, line.split())) for line in lines]
    return np.array(dataset)

file_path = '/content/fars.txt'  # Replace with the correct path to your text file
original_dataset = load_dataset(file_path)

# Step 2: Convert dataset to bipolar encoding based on the specified condition
def convert_to_bipolar_with_condition(dataset):
    return np.where(dataset > 128, -1, 1)

bipolar_dataset = convert_to_bipolar_with_condition(original_dataset)

# Step 3: Reshape each sequence into a matrix
num_fonts = 7
sequence_length = 17

# Reshape each sequence into a 2D matrix
matrix_dataset = bipolar_dataset.reshape(-1, num_fonts, sequence_length)

# Print the original, bipolar, and matrix datasets for verification
print("Original Dataset:")
print(original_dataset)

print("\nBipolar Encoded Dataset:")
print(bipolar_dataset)

print("\nMatrix Dataset:")
print(matrix_dataset)


Original Dataset:
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]

Bipolar Encoded Dataset:
[[-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 ...
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]]

Matrix Dataset:
[[[-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  ...
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]]

 [[-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  ...
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]]

 [[-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  ...
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]]

 ...

 [[-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  ...
  [-1 -1 

In [4]:
import numpy as np

# Step 1: Load and preprocess the dataset
file_path = '/content/fars.txt'  # Replace with the correct path to your text file
original_dataset = np.loadtxt(file_path)

# Convert to bipolar encoding (-1 or 1)
bipolar_dataset = np.where(original_dataset > 128, -1, 1)

num_characters = 17
num_fonts = 7
input_size = 95 * 95

# Reshape each character with different fonts into a matrix
character_matrices = bipolar_dataset.reshape(num_characters, num_fonts, 95, 95)

# Flatten each matrix to create input vectors
input_vectors = character_matrices.reshape(num_characters * num_fonts, -1)

# Step 2: Build a simple perceptron network with random weights
num_weights = input_size
weights = np.random.randn(num_weights, 1)

# Step 3: Define activation function (sigmoid) and forward pass
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def forward_pass(data, weights):
    return sigmoid(np.dot(data, weights))

# Step 4: Train the perceptron network for 10 epochs
epochs = 10

for epoch in range(epochs):
    for char_font_idx in range(num_characters * num_fonts):
        # Select the input vector for the current character and font
        input_vector = input_vectors[char_font_idx, :]

        # Forward pass
        output = forward_pass(input_vector, weights)

        # Convert output to bipolar (-1 or 1)
        output_bipolar = np.where(output > 0.5, 1, -1)

        # Update weights (dummy update, not based on any real learning algorithm)
        weights += np.random.randn(num_weights, 1) * 0.01  # Adjust the learning rate as needed

# Step 5: Make predictions for each character and font
predictions = np.zeros((num_characters, num_fonts))

for char_idx in range(num_characters):
    for font_idx in range(num_fonts):
        input_vector = input_vectors[char_idx * num_fonts + font_idx, :]
        predictions[char_idx, font_idx] = np.where(forward_pass(input_vector, weights) > 0.5, 1, -1)

# Print predictions for verification
print("Predictions:")
print(predictions)


Predictions:
[[-1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1.  1. -1. -1. -1.]
 [-1. -1. -1. -1.  1. -1.  1.]
 [-1. -1. -1.  1. -1. -1. -1.]
 [-1. -1. -1. -1.  1. -1. -1.]
 [-1. -1. -1. -1.  1. -1. -1.]
 [-1. -1. -1. -1.  1.  1. -1.]
 [-1. -1. -1. -1.  1. -1. -1.]
 [-1. -1. -1.  1.  1. -1.  1.]
 [-1. -1. -1.  1. -1. -1. -1.]
 [-1. -1.  1. -1.  1. -1. -1.]
 [-1. -1. -1. -1. -1.  1.  1.]
 [-1. -1. -1. -1.  1. -1. -1.]
 [-1. -1. -1. -1.  1.  1.  1.]
 [-1. -1. -1. -1.  1.  1. -1.]
 [-1. -1. -1.  1.  1. -1. -1.]
 [-1. -1. -1. -1.  1. -1.  1.]]


In [5]:
import numpy as np

# Step 1: Load and preprocess the dataset
file_path = '/content/fars.txt'  # Replace with the correct path to your text file
original_dataset = np.loadtxt(file_path)

# Convert to bipolar encoding (-1 or 1)
bipolar_dataset = np.where(original_dataset > 128, -1, 1)

num_characters = 17
num_fonts = 7
input_size = 95 * 95

# Reshape each character with different fonts into a matrix
character_matrices = bipolar_dataset.reshape(num_characters, num_fonts, 95, 95)

# Flatten each matrix to create input vectors
input_vectors = character_matrices.reshape(num_characters * num_fonts, -1)

# Step 2: Build a simple perceptron network with random weights
num_weights = input_size
weights = np.random.randn(num_weights, 1)

# Step 3: Define activation function (sigmoid) and forward pass
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def forward_pass(data, weights):
    return sigmoid(np.dot(data, weights))

# Step 4: Train the perceptron network for 10 epochs
epochs = 10

for epoch in range(epochs):
    for char_font_idx in range(num_characters * num_fonts):
        # Select the input vector for the current character and font
        input_vector = input_vectors[char_font_idx, :]

        # Forward pass
        output = forward_pass(input_vector, weights)

        # Convert output to bipolar (-1 or 1)
        output_bipolar = np.where(output > 0.5, 1, -1)

        # Update weights (dummy update, not based on any real learning algorithm)
        weights += np.random.randn(num_weights, 1) * 0.01  # Adjust the learning rate as needed

# Step 5: Make predictions for each character and font
predictions = np.zeros((num_characters, num_fonts), dtype=bool)

for char_idx in range(num_characters):
    for font_idx in range(num_fonts):
        input_vector = input_vectors[char_idx * num_fonts + font_idx, :]
        predictions[char_idx, font_idx] = np.any(forward_pass(input_vector, weights) > 0.5)

# Print predictions for verification
print("Predictions:")
print(predictions)



Predictions:
[[ True  True  True False False  True  True]
 [ True  True  True  True  True False  True]
 [ True  True  True  True  True  True False]
 [ True  True  True  True False  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True False False False  True]
 [ True  True  True  True False False  True]
 [ True  True  True False False False  True]
 [ True  True  True  True  True  True False]
 [ True  True  True  True False False  True]
 [ True False  True False False False  True]
 [ True  True  True False False False  True]
 [ True  True  True False False False False]
 [ True  True  True False False False  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True False  True  True  True]
 [ True  True  True  True  True False  True]]


In [6]:
import numpy as np

# Step 1: Load and preprocess the dataset
file_path = '/content/fars.txt'  # Replace with the correct path to your text file
original_dataset = np.loadtxt(file_path)

# Convert to bipolar encoding (-1 or 1)
bipolar_dataset = np.where(original_dataset > 128, -1, 1)

num_characters = 17
num_fonts = 7
input_size = 95 * 95

# Reshape each character with different fonts into a matrix
character_matrices = bipolar_dataset.reshape(num_characters, num_fonts, 95, 95)
print(character_matrices)
# Flatten each matrix to create input vectors
input_vectors = character_matrices.reshape(num_characters * num_fonts, -1)
print(input_vectors)
# Create target labels (true if the character is present in any font)
target_labels = np.zeros((num_characters, num_fonts), dtype=int)
for char_idx in range(num_characters):
    random_font_idx = np.random.randint(num_fonts)  # Randomly select a font for each character
    target_labels[char_idx, random_font_idx] = 1

# Step 2: Build a simple perceptron network with random weights
num_weights = input_size
weights = np.random.randn(num_weights, 1)

# Step 3: Define activation function (sigmoid) and forward pass
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def forward_pass(data, weights):
    return sigmoid(np.dot(data, weights))

# Step 4: Train the perceptron network for 10 epochs
epochs = 10
learning_rate = 0.01

for epoch in range(epochs):
    for char_font_idx in range(num_characters * num_fonts):
        # Select the input vector for the current character and font
        input_vector = input_vectors[char_font_idx, :].reshape(1, -1)

        # Select the target label for the current character and font
        target_label = target_labels[char_font_idx // num_fonts, char_font_idx % num_fonts]

        # Forward pass
        output = forward_pass(input_vector, weights)

        # Update weights using perceptron learning rule
        weights += learning_rate * (target_label - output) * input_vector.T

# Step 5: Make predictions for each character and font
predictions = np.zeros((num_characters, num_fonts), dtype=int)

for char_idx in range(num_characters):
    for font_idx in range(num_fonts):
        input_vector = input_vectors[char_idx * num_fonts + font_idx, :].reshape(1, -1)
        predictions[char_idx, font_idx] = int(forward_pass(input_vector, weights) > 0.5)

# Print predictions and target labels for verification
print("Predictions:")
print(predictions)
print("\nTarget Labels:")
print(target_labels)


[[[[-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   ...
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]]

  [[-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   ...
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]]

  [[-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   ...
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]]

  ...

  [[-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   ...
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]]

  [[-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   ...
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]]

  [[-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   ...
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 

In [7]:
import numpy as np

# Step 1: Load and preprocess the dataset
file_path = '/content/fars.txt'  # Replace with the correct path to your text file
original_dataset = np.loadtxt(file_path)

# Convert to bipolar encoding (-1 or 1)
bipolar_dataset = np.where(original_dataset > 128, -1, 1)

num_characters = 17
num_fonts = 7
input_size = 95 * 95

# Reshape each character with different fonts into a matrix
character_matrices = bipolar_dataset.reshape(num_characters, num_fonts, 95, 95)
print(character_matrices)
# Flatten each matrix to create input vectors
input_vectors = character_matrices.reshape(num_characters * num_fonts, -1)
print(input_vectors)

# Add bias term to input vectors
input_vectors_with_bias = np.c_[input_vectors, np.ones((num_characters * num_fonts, 1))]  # Adding a column of ones for bias

# Create target labels (true if the character is present in any font)
target_labels = np.zeros((num_characters, num_fonts), dtype=int)
for char_idx in range(num_characters):
    random_font_idx = np.random.randint(num_fonts)  # Randomly select a font for each character
    target_labels[char_idx, random_font_idx] = 1

# Step 2: Build a simple perceptron network with random weights
num_weights = input_size + 1  # Additional weight for bias
weights = np.random.randn(num_weights, 1)

# Step 3: Define activation function (sigmoid) and forward pass
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def forward_pass(data, weights):
    return sigmoid(np.dot(data, weights))

# Step 4: Train the perceptron network for 10 epochs
epochs = 10
learning_rate = 0.01

for epoch in range(epochs):
    for char_font_idx in range(num_characters * num_fonts):
        # Select the input vector for the current character and font
        input_vector = input_vectors_with_bias[char_font_idx, :].reshape(1, -1)

        # Select the target label for the current character and font
        target_label = target_labels[char_font_idx // num_fonts, char_font_idx % num_fonts]

        # Forward pass
        output = forward_pass(input_vector, weights)

        # Update weights using perceptron learning rule
        weights += learning_rate * (target_label - output) * input_vector.T

# Step 5: Make predictions for each character and font
predictions = np.zeros((num_characters, num_fonts), dtype=int)

for char_idx in range(num_characters):
    for font_idx in range(num_fonts):
        input_vector = input_vectors_with_bias[char_idx * num_fonts + font_idx, :].reshape(1, -1)
        predictions[char_idx, font_idx] = int(forward_pass(input_vector, weights) > 0.5)

# Print predictions and target labels for verification
print("Predictions:")
print(predictions)
print("\nTarget Labels:")
print(target_labels)

# Calculate accuracy
accuracy = np.sum(predictions == target_labels) / (num_characters * num_fonts)
print("\nAccuracy:", accuracy)


[[[[-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   ...
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]]

  [[-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   ...
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]]

  [[-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   ...
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]]

  ...

  [[-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   ...
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]]

  [[-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   ...
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]]

  [[-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 -1]
   ...
   [-1 -1 -1 ... -1 -1 -1]
   [-1 -1 -1 ... -1 -1 

In [8]:
import numpy as np
from sklearn.model_selection import train_test_split

# ... (previous code remains the same)

# Split the data into training and testing sets
test_size = 0.2  # You can adjust this proportion based on your dataset size
X_train, X_test, y_train, y_test = train_test_split(input_vectors_with_bias, target_labels.flatten(), test_size=test_size, random_state=42)

# Step 2: Build a simple perceptron network with random weights
num_weights = input_size + 1  # Additional weight for bias
weights = np.random.randn(num_weights, 1)

# Step 3: Define activation function (sigmoid) and forward pass
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def forward_pass(data, weights):
    return sigmoid(np.dot(data, weights))

# Step 4: Train the perceptron network for 10 epochs
epochs = 10
learning_rate = 0.01

for epoch in range(epochs):
    for idx in range(len(X_train)):
        # Select the input vector for the current sample
        input_vector = X_train[idx, :].reshape(1, -1)

        # Select the target label for the current sample
        target_label = y_train[idx]

        # Forward pass
        output = forward_pass(input_vector, weights)

        # Update weights using perceptron learning rule
        weights += learning_rate * (target_label - output) * input_vector.T

# Step 5: Make predictions on the test set
predictions = np.zeros_like(y_test)

for idx in range(len(X_test)):
    input_vector = X_test[idx, :].reshape(1, -1)
    predictions[idx] = int(forward_pass(input_vector, weights) > 0.5)

# Calculate accuracy on the test set
accuracy = np.sum(predictions == y_test) / len(y_test)
print("\nAccuracy on Test Set:", accuracy)



Accuracy on Test Set: 0.9166666666666666
