<a href="https://colab.research.google.com/github/fjadidi2001/Artificial_Intelligence_Learning/blob/master/soft_computing_alphabet_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# Sample dataset of alphabets
data = {
    'character': ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'],
    'label': ['lowercase'] * 26
}
df = pd.DataFrame(data)

# Feature extraction
vectorizer = CountVectorizer(analyzer='char')
X = vectorizer.fit_transform(df['character'])

# Target variable
y = df['label']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the model
model = MultinomialNB()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Model accuracy: {accuracy}")

# Recognize alphabet function
def recognize_alphabet(input_char):
    input_vector = vectorizer.transform([input_char])
    prediction = model.predict(input_vector)
    if prediction[0] == 'lowercase':
        print(f"{input_char} belongs to the lowercase alphabet")
    else:
        print(f"{input_char} does not belong to the lowercase alphabet")

# Test the recognition function
input_char = 'a'
recognize_alphabet(input_char)


Model accuracy: 1.0
a belongs to the lowercase alphabet


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from google.colab import drive

drive.mount('/content/drive')

# Read the text file
file_path = '/content/fars.txt'
with open(file_path, 'r') as file:
    data = file.read().splitlines()

# Create a pandas dataframe from the data
df = pd.DataFrame(data, columns=['character'])

# Add labels to the dataframe
df['label'] = df['character'].apply(lambda x: 'lowercase' if x.islower() else 'uppercase')

# Feature extraction
vectorizer = CountVectorizer(analyzer='word', lowercase=False)
X = vectorizer.fit_transform(df['character'])

# Target variable
y = df['label']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the model
model = MultinomialNB()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Model accuracy: {accuracy}")

# Recognize alphabet function
def recognize_alphabet(input_char):
    if input_char.islower():
        print(f"{input_char} belongs to the lowercase alphabet")
    else:
        print(f"{input_char} belongs to the uppercase alphabet")

# Test the recognition function
input_char = 'a'
recognize_alphabet(input_char)


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Model accuracy: 1.0
a belongs to the lowercase alphabet


In [ ]:
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM, Dense, Embedding
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

# Preprocess the code snippets and convert them into numerical sequences
tokenizer = Tokenizer()
tokenizer.fit_on_texts(code_snippets)
sequences = tokenizer.texts_to_sequences(code_snippets)
max_sequence_length = max(len(seq) for seq in sequences)
padded_sequences = pad_sequences(sequences, maxlen=max_sequence_length)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(padded_sequences, labels, test_size=0.2, random_state=42)

# Build the LSTM model
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_sequence_length))
model.add(LSTM(128))
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Model accuracy: {accuracy}")

# Make predictions
new_code_snippet = preprocess_and_tokenize(new_code)
prediction = model.predict(new_code_snippet)


"""
In this example, you would need to replace code_snippets
with your actual preprocessed data and labels with the corresponding labels
for pixel manipulation. Additionally, you may need to adjust the model architecture,
hyperparameters, and preprocessing steps based on the specifics of your problem and data.
"""


NameError: ignored

In [ ]:
import numpy as np
from sklearn.cluster import KMeans
from scipy.spatial.distance import cdist
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge
from sklearn.metrics.pairwise import rbf_kernel

# Load the pixel representations from the text file and convert them to a matrix format
# Assuming the data is in a suitable format, you may need to customize this step based on the actual data format

# Preprocess the data and split it into features (X) and labels (y)
X = ...  # Pixel matrix representations
y = ...  # Uppercase/lowercase labels

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Design the RBF network architecture
num_rbf_neurons = 50  # Number of RBF neurons
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)

# Initialize RBF neuron centers using K-means clustering
kmeans = KMeans(n_clusters=num_rbf_neurons, random_state=0).fit(X_train)
rbf_centers = kmeans.cluster_centers_

# Compute RBF neuron widths
distances = cdist(X_train, rbf_centers, 'euclidean')
rbf_widths = np.std(distances)

# Compute RBF neuron activations
rbf_activations = rbf_kernel(X_train, rbf_centers, gamma=1.0 / (2 * (rbf_widths ** 2)))

# Solve for the output weights using Ridge regression
ridge = Ridge(alpha=1e-6, fit_intercept=True)
ridge.fit(rbf_activations, y_train_encoded)

# Test the trained RBF network
# Compute RBF neuron activations for the testing data
rbf_activations_test = rbf_kernel(X_test, rbf_centers, gamma=1.0 / (2 * (rbf_widths ** 2)))

# Make predictions using the output weights
y_pred_encoded = ridge.predict(rbf_activations_test)
y_pred = encoder.inverse_transform(y_pred_encoded)

# Evaluate the performance of the RBF network
accuracy = accuracy_score(y_test, y_pred)
print(f"RBF network accuracy: {accuracy}")


In [ ]:
import numpy as np

# Step 1: Load the dataset from a text file
def load_dataset(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()
    dataset = [list(map(int, line.split())) for line in lines]
    return np.array(dataset)

file_path = '/content/fars.txt'  # Provide the correct path to your text file
original_dataset = load_dataset(file_path)

# Step 2: Convert dataset to bipolar encoding based on the specified condition
def convert_to_bipolar_with_condition(dataset):
    return np.where(dataset > 128, -1, 1)

bipolar_dataset = convert_to_bipolar_with_condition(original_dataset)

# Print original and bipolar datasets for verification
print("Original Dataset:")
print(original_dataset)

print("\nBipolar Encoded Dataset:")
print(bipolar_dataset)


Original Dataset:
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]

Bipolar Encoded Dataset:
[[-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 ...
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]]


In [ ]:
import numpy as np

# Step 1: Load the dataset from a text file
def load_dataset(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()
    dataset = [list(map(int, line.split())) for line in lines]
    return np.array(dataset)

file_path = '/content/fars.txt'  # Replace with the correct path to your text file
original_dataset = load_dataset(file_path)

# Step 2: Reshape each sequence into a matrix
num_fonts = 7
sequence_length = 17

# Reshape each sequence into a 2D matrix
matrix_dataset = original_dataset.reshape(-1, num_fonts, sequence_length)

# Print the original and matrix datasets for verification
print("Original Dataset:")
print(original_dataset)

print("\nMatrix Dataset:")
print(matrix_dataset)


Original Dataset:
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]

Matrix Dataset:
[[[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]]

 [[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]]

 [[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]]

 ...

 [[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
 

In [ ]:
import numpy as np

# Step 1: Load the dataset from a text file
def load_dataset(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()
    dataset = [list(map(int, line.split())) for line in lines]
    return np.array(dataset)

file_path = '/content/fars.txt'  # Replace with the correct path to your text file
original_dataset = load_dataset(file_path)

# Step 2: Convert dataset to bipolar encoding based on the specified condition
def convert_to_bipolar_with_condition(dataset):
    return np.where(dataset > 128, -1, 1)

bipolar_dataset = convert_to_bipolar_with_condition(original_dataset)

# Step 3: Reshape each sequence into a matrix
num_fonts = 7
sequence_length = 17

# Reshape each sequence into a 2D matrix
matrix_dataset = bipolar_dataset.reshape(-1, num_fonts, sequence_length)

# Print the original, bipolar, and matrix datasets for verification
print("Original Dataset:")
print(original_dataset)

print("\nBipolar Encoded Dataset:")
print(bipolar_dataset)

print("\nMatrix Dataset:")
print(matrix_dataset)


Original Dataset:
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]

Bipolar Encoded Dataset:
[[-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 ...
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]]

Matrix Dataset:
[[[-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  ...
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]]

 [[-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  ...
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]]

 [[-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  ...
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]]

 ...

 [[-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  ...
  [-1 -1 

In [ ]:
import numpy as np

# Step 1: Load and preprocess the dataset
file_path = '/content/fars.txt'  # Replace with the correct path to your text file
original_dataset = np.loadtxt(file_path)

def convert_to_bipolar_with_condition(dataset):
    return np.where(dataset > 128, -1, 1)

bipolar_dataset = convert_to_bipolar_with_condition(original_dataset)

num_fonts = 7
input_size = 95 * 95

# Reshape each sequence into a 2D matrix
input_data = bipolar_dataset.reshape(-1, num_fonts, 95, 95)

# Step 2: Build a simple neural network with random weights
hidden_size = 64
output_size = 1

# Initialize random weights and biases
weights_hidden = np.random.randn(input_size, hidden_size)
biases_hidden = np.zeros((1, hidden_size))
weights_output = np.random.randn(hidden_size, output_size)
biases_output = np.zeros((1, output_size))

# Step 3: Define activation function (sigmoid) and forward pass
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def forward_pass(data):
    data_flattened = data.reshape(-1, input_size)
    hidden_layer_input = np.dot(data_flattened, weights_hidden) + biases_hidden
    hidden_layer_output = sigmoid(hidden_layer_input)
    output_layer_input = np.dot(hidden_layer_output, weights_output) + biases_output
    output = sigmoid(output_layer_input)
    return output

# Step 4: Train the neural network (random weights, so not meaningful)
# Assuming you have labels for your data (binary classification)
labels = np.random.randint(0, 2, size=(input_data.shape[0], 1))

# Perform a forward pass (no backpropagation or weight updates in this simple example)
predictions = forward_pass(input_data)

# Print predictions for verification
print("Predictions:")
print(predictions)


Predictions:
[[0.3291297 ]
 [0.3291297 ]
 [0.0854868 ]
 [0.93299217]
 [0.82351583]
 [0.34827895]
 [0.3291297 ]
 [0.3291297 ]
 [0.3291297 ]
 [0.3291297 ]
 [0.07285459]
 [0.18752605]
 [0.28799974]
 [0.3291297 ]
 [0.3291297 ]
 [0.3291297 ]
 [0.3291297 ]
 [0.87022639]
 [0.00725343]
 [0.94424744]
 [0.99094004]
 [0.3291297 ]
 [0.3291297 ]
 [0.4592532 ]
 [0.92735167]
 [0.93935015]
 [0.83563282]
 [0.27773484]
 [0.3291297 ]
 [0.3291297 ]
 [0.3291297 ]
 [0.17637049]
 [0.48409341]
 [0.04765104]
 [0.13602017]
 [0.3291297 ]
 [0.3291297 ]
 [0.3291297 ]
 [0.9331633 ]
 [0.95340968]
 [0.10107802]
 [0.06086342]
 [0.3291297 ]
 [0.3291297 ]
 [0.3291297 ]
 [0.76620982]
 [0.99637036]
 [0.96667494]
 [0.04062386]
 [0.3291297 ]
 [0.2830179 ]
 [0.04601785]
 [0.00645116]
 [0.13320435]
 [0.91156307]
 [0.3291297 ]
 [0.3291297 ]
 [0.3291297 ]
 [0.17961895]
 [0.53269958]
 [0.89264076]
 [0.99355953]
 [0.91357556]
 [0.3291297 ]
 [0.3291297 ]
 [0.24412919]
 [0.00365142]
 [0.49640472]
 [0.569527  ]
 [0.3291297 ]
 [0.329

In [ ]:
import numpy as np

# Step 1: Load and preprocess the dataset
file_path = '/content/fars.txt'  # Replace with the correct path to your text file
original_dataset = np.loadtxt(file_path)

# Convert to bipolar encoding (-1 or 1)
bipolar_dataset = np.where(original_dataset > 128, -1, 1)

num_characters = 17
num_fonts = 7
input_size = 95 * 95

# Reshape each character with different fonts into a matrix
character_matrices = bipolar_dataset.reshape(num_characters, num_fonts, input_size)
# print(character_matrices)

# Flatten each matrix to create input vectors
input_vectors = character_matrices.reshape(num_characters, -1)

# Step 2: Build a simple perceptron network with random weights
num_weights = input_size
weights = np.random.randn(num_weights, 1)

# Step 3: Define activation function (sigmoid) and forward pass
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def forward_pass(data, weights):
    return sigmoid(np.dot(data, weights))

# Step 4: Train the perceptron network for 10 epochs
epochs = 10

for epoch in range(epochs):
    for char_idx in range(num_characters):
        for font_idx in range(num_fonts):
            # Select the input vector for the current character and font
            input_vector = input_vectors[char_idx, font_idx, :]

            # Forward pass
            output = forward_pass(input_vector, weights)

            # Update weights (dummy update, not based on any real learning algorithm)
            weights += np.random.randn(num_weights, 1) * 0.01  # Adjust the learning rate as needed

# Step 5: Make predictions for each character and font
predictions = np.zeros((num_characters, num_fonts))

for char_idx in range(num_characters):
    for font_idx in range(num_fonts):
        input_vector = input_vectors[char_idx, font_idx, :]
        predictions[char_idx, font_idx] = forward_pass(input_vector, weights)

# Print predictions for verification
print("Predictions:")
print(predictions)


In [ ]:
import numpy as np

# Step 1: Load and preprocess the dataset
file_path = '/content/fars.txt'  # Replace with the correct path to your text file
original_dataset = np.loadtxt(file_path)

# Convert to bipolar encoding (-1 or 1)
bipolar_dataset = np.where(original_dataset > 128, -1, 1)

num_characters = 17
num_fonts = 7
input_size = 95 * 95

# Reshape each character with different fonts into a matrix
character_matrices = bipolar_dataset.reshape(num_characters, num_fonts, 95, 95)

# Flatten each matrix to create input vectors
input_vectors = character_matrices.reshape(num_characters * num_fonts, -1)

# Step 2: Build a simple perceptron network with random weights
num_weights = input_size
weights = np.random.randn(num_weights, 1)

# Step 3: Define activation function (sigmoid) and forward pass
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def forward_pass(data, weights):
    return sigmoid(np.dot(data, weights))

# Step 4: Train the perceptron network for 10 epochs
epochs = 10

for epoch in range(epochs):
    for char_font_idx in range(num_characters * num_fonts):
        # Select the input vector for the current character and font
        input_vector = input_vectors[char_font_idx, :]

        # Forward pass
        output = forward_pass(input_vector, weights)

        # Update weights (dummy update, not based on any real learning algorithm)
        weights += np.random.randn(num_weights, 1) * 0.01  # Adjust the learning rate as needed

# Step 5: Make predictions for each character and font
predictions = np.zeros((num_characters, num_fonts))

for char_idx in range(num_characters):
    for font_idx in range(num_fonts):
        input_vector = input_vectors[char_idx * num_fonts + font_idx, :]
        predictions[char_idx, font_idx] = forward_pass(input_vector, weights)

# Print predictions for verification
print("Predictions:")
print(predictions)


Predictions:
[[9.99999999e-01 9.99999999e-01 9.99990211e-01 1.00000000e+00
  6.93071461e-29 1.00000000e+00 9.99999999e-01]
 [9.99999999e-01 9.99999999e-01 9.99999999e-01 1.00000000e+00
  6.30675936e-25 1.00000000e+00 9.99999999e-01]
 [9.99999999e-01 9.99999999e-01 9.99999999e-01 1.00000000e+00
  2.12161405e-08 1.00000000e+00 3.50337551e-42]
 [9.99999999e-01 9.99999999e-01 1.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00 9.99999999e-01]
 [9.99999999e-01 9.99999999e-01 9.99999999e-01 1.00000000e+00
  1.00000000e+00 9.99999610e-01 9.99999992e-01]
 [9.99999999e-01 9.99999999e-01 9.99999999e-01 1.00000000e+00
  2.94083991e-10 2.50683270e-17 9.92651736e-01]
 [9.99999999e-01 9.99999999e-01 9.99999999e-01 1.00000000e+00
  1.00000000e+00 2.53696036e-12 1.02337196e-09]
 [9.99999999e-01 9.99999695e-01 1.48815743e-04 1.00000000e+00
  1.00000000e+00 1.00000000e+00 9.99999999e-01]
 [9.99999999e-01 9.99999999e-01 1.00000000e+00 9.75734483e-01
  1.00000000e+00 1.00000000e+00 9.99999620e-0

In [13]:
import numpy as np

# Step 1: Load and preprocess the dataset
file_path = '/content/fars.txt'  # Replace with the correct path to your text file
original_dataset = np.loadtxt(file_path)

# Convert to bipolar encoding (-1 or 1)
bipolar_dataset = np.where(original_dataset > 128, -1, 1)

num_characters = 17
num_fonts = 7
input_size = 95 * 95

# Reshape each character with different fonts into a matrix
character_matrices = bipolar_dataset.reshape(num_characters, num_fonts, 95, 95)

# Flatten each matrix to create input vectors
input_vectors = character_matrices.reshape(num_characters * num_fonts, -1)

# Step 2: Build a simple perceptron network with random weights
num_weights = input_size
weights = np.random.randn(num_weights, 1)

# Step 3: Define activation function (sigmoid) and forward pass
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def forward_pass(data, weights):
    return sigmoid(np.dot(data, weights))

# Step 4: Train the perceptron network for 10 epochs
epochs = 10

for epoch in range(epochs):
    for char_font_idx in range(num_characters * num_fonts):
        # Select the input vector for the current character and font
        input_vector = input_vectors[char_font_idx, :]

        # Forward pass
        output = forward_pass(input_vector, weights)

        # Convert output to bipolar (-1 or 1)
        output_bipolar = np.where(output > 0.5, 1, -1)

        # Update weights (dummy update, not based on any real learning algorithm)
        weights += np.random.randn(num_weights, 1) * 0.01  # Adjust the learning rate as needed

# Step 5: Make predictions for each character and font
predictions = np.zeros((num_characters, num_fonts))

for char_idx in range(num_characters):
    for font_idx in range(num_fonts):
        input_vector = input_vectors[char_idx * num_fonts + font_idx, :]
        predictions[char_idx, font_idx] = np.where(forward_pass(input_vector, weights) > 0.5, 1, -1)

# Print predictions for verification
print("Predictions:")
print(predictions)


Predictions:
[[ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1. -1.  1.  1.]
 [ 1.  1.  1.  1.  1. -1. -1.]
 [ 1.  1.  1. -1.  1.  1.  1.]
 [ 1.  1.  1. -1.  1.  1. -1.]
 [ 1.  1.  1.  1.  1.  1. -1.]
 [ 1.  1.  1.  1. -1. -1. -1.]
 [ 1.  1.  1. -1.  1.  1.  1.]
 [ 1.  1.  1. -1.  1. -1. -1.]
 [ 1.  1. -1.  1. -1.  1.  1.]
 [ 1.  1. -1. -1. -1.  1.  1.]
 [ 1.  1. -1. -1. -1.  1. -1.]
 [ 1.  1.  1.  1. -1. -1. -1.]
 [ 1.  1.  1. -1. -1.  1. -1.]
 [ 1.  1.  1. -1. -1. -1.  1.]
 [ 1.  1.  1.  1. -1.  1.  1.]
 [ 1.  1.  1. -1.  1. -1. -1.]]


In [18]:
import numpy as np

# Step 1: Load and preprocess the dataset
file_path = '/content/fars.txt'  # Replace with the correct path to your text file
original_dataset = np.loadtxt(file_path)

# Convert to bipolar encoding (-1 or 1)
bipolar_dataset = np.where(original_dataset > 128, -1, 1)

num_characters = 17
num_fonts = 7
input_size = 95 * 95

# Reshape each character with different fonts into a matrix
character_matrices = bipolar_dataset.reshape(num_characters, num_fonts, 95, 95)

# Flatten each matrix to create input vectors
input_vectors = character_matrices.reshape(num_characters * num_fonts, -1)

# Step 2: Build a simple perceptron network with random weights
num_weights = input_size
weights = np.random.randn(num_weights, 1)

# Step 3: Define activation function (sigmoid) and forward pass
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def forward_pass(data, weights):
    return sigmoid(np.dot(data, weights))

# Step 4: Train the perceptron network for 10 epochs
epochs = 10

for epoch in range(epochs):
    for char_font_idx in range(num_characters * num_fonts):
        # Select the input vector for the current character and font
        input_vector = input_vectors[char_font_idx, :]

        # Forward pass
        output = forward_pass(input_vector, weights)

        # Convert output to bipolar (-1 or 1)
        output_bipolar = np.where(output > 0.5, 1, -1)

        # Update weights (dummy update, not based on any real learning algorithm)
        weights += np.random.randn(num_weights, 1) * 0.01  # Adjust the learning rate as needed

# Step 5: Make predictions for each character and font
predictions = np.zeros((num_characters, num_fonts), dtype=bool)

for char_idx in range(num_characters):
    for font_idx in range(num_fonts):
        input_vector = input_vectors[char_idx * num_fonts + font_idx, :]
        predictions[char_idx, font_idx] = np.any(forward_pass(input_vector, weights) > 0.5)

# Print predictions for verification
print("Predictions:")
print(predictions)



Predictions:
[[False False  True  True False False False]
 [False False False  True False False False]
 [False False False  True  True False False]
 [False False False  True False False False]
 [False False False False False False False]
 [False False False False  True False False]
 [False False False  True  True False False]
 [False False False  True  True False False]
 [False False False False  True False False]
 [False False False  True  True False False]
 [False False False  True  True False False]
 [False False False False False False False]
 [False False False False  True False False]
 [False False False False  True False False]
 [False False False False False  True False]
 [False False False  True  True False False]
 [False False False False  True False False]]
